version: '3'
services:
  postgres:
    ports:
      - "5432:5432"
    image: postgres
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=db
  app:
    depends_on:
      - postgres
      - kafka
    ports:
      - 8080:8080
    build:
      dockerfile: ./build/Dockerfile
      context: ..
    volumes:
      - ../log:/log
  zookeeper:
    image: bitnami/zookeeper:3.5.6
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:2.3.0
    depends_on:
      - zookeeper
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181